name: "Bump.sh API Documentation & Changelog"
description: |
  Keep your public, private and partner API docs in sync with your code, whether you use OpenAPI or AsyncAPI.
author: bump.sh

inputs:
  file:
    description: "Relative path to an API definition file (OpenAPI or AsyncAPI) or a directory of definition files (when deploying to a Hub)"
    required: true
    default: api-contract.yml
  doc:
    description: "Documentation slug or id. Can be found in the documentation settings on https://bump.sh"
  token:
    description: "Api token. Can be found in the documentation or organization settings on https://bump.sh"
  hub:
    description: "Hub slug or id. Needed when deploying to a documentation attached to a Hub. Can be found in the hub settings on https://bump.sh"
  branch:
    description: "Branch name used during `deploy` or `diff` commands. This can be useful to maintain multiple API reference history and make it available in your API documentation."
  command:
    description: "Bump command: deploy|dry-run|preview|diff"
    default: deploy
  expires:
    description: "Specify a longer expiration date for public diffs (defaults to 1 day). Use iso8601 format to provide a date, or you can use `never` to keep the result live indefinitely."
  fail_on_breaking:
    description: "Mark the action as failed when a breaking change is detected with the diff command. This is only valid when `diff` is provided in the command input."
    default: false
  overlay:
    description: "A list of OpenAPI Overlays to apply to the API definition before deploying it. Overlays are applied in the order they are provided."
  filename_pattern:
    default: "{slug}-api"
    description: "Filename pattern to extract the documentation slug from filenames when deploying a DIRECTORY. Pattern uses only '*' and '{slug}' as special characters to extract the slug from a filename without extension. Only used with the 'hub' input when deploying a whole directory ."
runs:
  using: node20
  main: dist/index.js

branding:
  color: gray-dark
  icon: book-open
