name: 'Bump.sh'
description: 'Keep your public, private and partner API docs in sync with your code, whether you use OpenAPI or AsyncAPI.'
inputs:
  file:
    description: 'Relative path to the documentation file'
    required: true
    default: api-contract.yml
  doc:
    description: 'Documentation id. Can be found in the documentation settings on https://bump.sh'
  token:
    description: 'Documentation token. Can be found in the documentation settings on https://bump.sh'
  hub:
    description: 'Hub slug or id. Needed when deploying to a documentation attached to a Hub. Can be found in the hub settings on https://bump.sh'
  branch:
    description: 'Branch name used during `deploy` or `diff` commands. This can be useful to maintain multiple API reference history and make it available in your API documentation.'
  command:
    description: 'Bump command: deploy/dry-run/preview'
    default: deploy
  expires:
    description: 'Specify a longer expiration date for public diffs (defaults to 1 day). Use iso8601 format to provide a date, or you can use `never` to keep the result live indefinitely.'
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  color: gray-dark
  icon: book-open
